### ISSUE TITLE
compatibility with postcss

### ISSUE THREAD

**Issue by zanona** [PepsRyuu/rollup-plugin-hot-css#1]
Hello,
By any chance would there be any compatibility issue when running hotcss wih postcss?

I have the following on my config:

```js
const plugins = [
  resolve(),
  json(),
  hotcss({
    hot: process.env.NODE_ENV !== 'production',
    filename: 'index.css',
    loaders: ['less']
  }),
  postcss({
    modules: {camelCase: true},
    extract: true,
    use:['less'],
    plugins: [ autoprefixer ]
  }),
  typescript(),
  commonjs({extensions: ['.js', '.ts', '.tsx']}),
];

```

But whenever running nollup I get a parsing error for the less file?
Thanks in advance

**Comment by PepsRyuu** [comment]
In terms of Rollup plugins, it wouldn't be allowed, as they would would both be trying to load CSS files and extracting them to a separate file, so you would end up with multiple CSS files. They would be fighting against each other.

In terms of PostCSS however, you can certainly get it to work. The ```loaders``` array takes a function. :) https://github.com/PepsRyuu/rollup-plugin-hot-css#loaders It gives you the code so you can pass that code into a PostCSS function.

**Comment by PepsRyuu** [comment]
I haven't tested this, but I assume something like the follow would work:

```
let autoprefixer = require('autoprefixer')
let postcss = require('postcss')

function PostCSSLoader (input, id) {
    return postcss([autoprefixer]).process(input.code).then(res => {
        return {
            code: res.code
        };
    });
}

hotcss({
    loaders: ['scss', PostCSSLoader]
})
```

**Comment by zanona** [comment]
Thanks for the suggestions @PepsRyuu, I tried it out but while also using Typescript with CSS modules, it was just getting a bunch of errors, unfortunately. In fact, even without postcss and only using the 'less' loader causing `rollup -c` to fail while `nollup -c` seemed to work fine.

**Comment by PepsRyuu** [comment]
Do you mean ```hot-css``` fails when using LESS by itself? What does the config look like?

**Comment by zanona** [comment]
Hey, @PepsRyuu. I found out it was actually a cache issue with node_modules. All worked well now following your suggestion. Thanks again.

**Comment by piotr-cz** [comment]
Code from https://github.com/PepsRyuu/rollup-plugin-hot-css/issues/1#issuecomment-625294324 worked for me, except that loader should return 

```js
return {
    code: res.css,
    map: res.map && res.map.toJSON(), // Not being saved at the moment
};
```

as defined [here](https://github.com/postcss/postcss/blob/7.0.32/lib/result.es6#L84)

PostCSS inttegration is quite handy and IMHO should be added to README

**Comment by piotr-cz** [comment]
One more thing: when the `url` option is true (default), the csstree will be used to parse loaders's output

**Comment by PepsRyuu** [comment]
Will add the example to the README. Added a note about the ```url``` option that it resolves afterwards and sourcemaps must be emitted for those to resolve correctly.

**Comment by piotr-cz** [comment]
Thanks.
I can't make source maps working but it's another issue
