### ISSUE TITLE
README instructions for link tag don't work

### ISSUE THREAD

**Issue by CreaturesInUnitards** [PepsRyuu/rollup-plugin-hot-css#11]
I needed to change the href to `styles.[hash].css` to make this work. Is that a problem with my config?

**Comment by PepsRyuu** [comment]
Nope that's correct, the output is based off the ```assetsFileName``` option, which the common setup will include a hash placeholder for. The hash is not replaced in dev because that would cause a more awkward config. Might make a note on it in the readme though! :)

**Comment by PepsRyuu** [comment]
Added clarification in README.
