### ISSUE TITLE
node-sass required, even if not used

### ISSUE THREAD

**Issue by high1** [PepsRyuu/rollup-plugin-hot-css#7]
It's possible to have PostCSS config without node-sass, but currently - I might be wrong - seems that when loader is 'scss', node-sass is required. Maybe if the loader is a function, this should not be a must?

**Comment by PepsRyuu** [comment]
If you specify ```scss``` you need to manually install ```node-sass```. This is intentional to minimise installed dependencies.

**Comment by high1** [comment]
Will it be used for scss processing? What if I don't want it to be - i.e. avoid it completely?

**Comment by PepsRyuu** [comment]
It'll run on all files the way it's currently written. I'm not sure I'm understanding the question. If there's no intention of using the loader, it should be removed from the loaders array.

**Comment by high1** [comment]
Maybe I'm wrong somewhere, I'm not that familiar with CSS processing tools, but I got the impression that PostCSS does not depend on node-sass for scss processing? I mean, there could be a pipeline of using just PostCSS without node-sass for processing scss, if I'm right - but I could be wrong, I must repeat that. Or maybe, that would be just css then, with scss like syntax?

**Comment by high1** [comment]
I did some more reading, and it seems that I was wrong - you can get some features of SCSS in CSS by using PostCSS plugins, but then the file extensions should be css. I'm sorry for bothering you due to my lack of knowledge about CSS/SCSS/PostCSS/node-sass itd...
